spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
