server:
  port: 8100
spring:
  application:
    name: spring-ai-knowledge-vector
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:8b
      embedding:
        model: nomic-embed-text:latest
    # 向量数据库配置
    vectorstore:
      elasticsearch:
        index-name: ollama-rag-embedding-index
        similarity: cosine
        dimensions: 768
  elasticsearch:
    uris: http://127.0.0.1:9200
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
