#memcache:
#  host: 127.0.0.1
#  port: 11211
#  initConn: 100
#  minConn: 20
#  maxConn: 1000
#  maintSleep: 50
#  nagel: false
#  socketTO: 3000
#  aliveCheck: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 数据库方言
#  cache:
#    type: ehcache
#    cache-names: ehcahe_demo
#    ehcache:
#      config: ehcache.xml
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
#    sentinel:  # 哨兵配置
#      master: mymaster
#      nodes: 192.168.60.72:26380,192.168.60.72:26381,192.168.60.72:26382
